apiVersion: v1
kind: Namespace
metadata:
  name: airadio
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.2.5
    path: "/volume1/docker"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: airadio
spec:
  storageClassName: ""
  volumeName: ollama-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: generated-audio-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.2.5
    path: "/volume1/radio"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: generated-audio-pvc
  namespace: airadio
spec:
  storageClassName: ""
  volumeName: generated-audio-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
