apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - 2.yaml
  - dj-library-api.yaml
  - icecast.yaml
  - webui/3-webui-deployment.yaml

namespace: airadio
